services:

  cms:
    image: ghcr.io/agundur-kde/bonsaipress:latest
    user: "${UID}:${GID}"
    ports:
      - "8080:80"
    volumes:
      - ./clients:/var/www/clients
      - ./current:/var/www/current

  preview:
    image: ghcr.io/agundur-kde/bonsaipress:latest
    user: "${UID}:${GID}"
    ports:
      - "8081:80"
    volumes:
      - ./clients:/var/www/clients
      - ./current:/var/www/current

  watcher:
    image: ghcr.io/agundur-kde/bonsaipress-watcher:latest
    user: "${UID}:${GID}"
    environment:
      - SASS_CREATE_MAP=${SASS_CREATE_MAP:-false}
    ports:
      - "8001:8001"
    volumes:
      - ./clients:/var/www/clients
      - ./current:/var/www/current
