services:

  cms:
    image: ghcr.io/agundur-kde/bonsaipress:latest
    build: .
    user: "${UID}:${GID}"
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/cms.conf:/etc/apache2/sites-enabled/000-default.conf

  preview:
    image: ghcr.io/agundur-kde/bonsaipress:latest
    build: .
    user: "${UID}:${GID}"
    ports:
      - "8081:80"
    volumes:
      - .:/var/www
      - ./docker/preview.conf:/etc/apache2/sites-enabled/000-default.conf

  watcher:
    image: ghcr.io/agundur-kde/bonsaipress-watcher:latest
    build:
      context: .
      dockerfile: docker/watcher/Dockerfile
    user: "${UID}:${GID}"
    environment:
      - SASS_CREATE_MAP=${SASS_CREATE_MAP:-false}
    ports:
      - "8001:8001"
    volumes:
      - .:/var/www
